logging:
  level: INFO

bus:
  maxsize: 100

apps:
  - name: CommandIngest
    class: fsw.apps.command_ingest.CommandIngestApp
    enabled: true
    priority: 10
    config: command_ingest.yml
  - name: TelemetryOutput
    class: fsw.apps.telemetry_output.TelemetryOutputApp
    enabled: true
    priority: 20
    config: telemetry_output.yml
  - name: TerminalBridge
    class: fsw.apps.terminal_bridge.TerminalBridgeApp
    enabled: true
    priority: 30
    config: terminal_bridge.yml
  - name: SensorApp
    class: test_comms.apps.sensor_app.SensorApp
    enabled: true
    priority: 40
    config: sensor_app.yml
